### ISSUE TITLE
sidebar buttons

### ISSUE THREAD

**Issue by AM-77** [TutorialEdge/tutorialedge.net#374]
There is a little problem in the sidebar buttons

![Screenshot from 2020-06-29 20-42-57](https://user-images.githubusercontent.com/18232579/86043658-4f0f4080-ba49-11ea-8140-879f0912f80e.png)

it can be solved by adding this rules to the existing ones in `sidebar.scss` and removing the inline styles
```css
.youtube-subscribe {
  a {
    img {
        width: 100%
    }
    display: block;
  }
}


```
